project:
  type: website
  output-dir: .

website:
  title: "Optimeet: web-app"
  navbar:
    left:
      - href: index.qmd
        text: Guide

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

